# this patch fixes the namespace in the clientConfig. It is generated as
# "system" and nothing seems to fix it.
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- clientConfig:
    service:
      name: cluster-baremetal-webhook-service
      namespace: openshift-machine-api
