
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: openshift-machine-api
spec:
  ports:
    - port: 443
      targetPort: 9443
  selector:
    k8s-app: cluster-baremetal-operator
